### ISSUE TITLE
Helper function: delete associated events when deleting a check

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go-python#12]
Now that we have support for basic CRUD operations on most of the API resources, it would be good to start adding helper functions for common operations. 

A customer has requested a helper function for optionally deleting associated events when deleting a check. 

Example: 

- a check named "helloworld" exists, and has generated several events 
- user deletes the "helloworld" check using the python library 
- user provides an optional flag to delete all of the "helloworld" events, which uses an Event [API `fieldSelector`](https://docs.sensu.io/sensu-go/latest/api/#field-selector) (e.g. `event.check.name == "helloworld"`) to select events to delete, and deletes them

**Comment by tadeboro** [comment]
I would propose we tackle a more generic scenario here that will also take care of the bulk deletion issue at hand.

What we could do is:

 1. teach resources how to fetch related resources, and
 2. provide a container that knows how to perform operations on all items.

Then we could do things like "fetch all checks that use certain asset" and "delete all events associated with a check". In code, this would look like this:

```
# Assuming we already know how to filter responses, the next two lines would return the same checks
checks = client.assets.get("my-asset").checks
checks = client.checks.list(field_selector=[Op.IN("my-asset", "runtime_assets")])

client.checks.get("my-check").events.delete()
# We could also write this as:
for e in client.events.list(field_selector=[Op.EQ("check.name", "my-check")]):
    e.delete()
```

This proposed solution does not exactly fit the requirements since it does not make it possible to delete events automatically, but I would argue that the following code should be close enough to the desired goal:

```
check.events.delete()
check.delete()
```

Does all this sound reasonable?
