### ISSUE TITLE
Helper function: labelSelectors and fieldSelectors

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go-python#13]
Now that we have support for basic CRUD operations on most of the API resources, it would be good to start adding helper functions for common operations.

A customer has requested a helper function for constructing [`labelSelectors`](https://docs.sensu.io/sensu-go/latest/api/#label-selector) and [`fieldSelectors`](https://docs.sensu.io/sensu-go/latest/api/#field-selector). 

Perhaps these helper methods could look something like: 

```python
# fetch all entities where entity.system.os = "linux"
client.entities.list().fieldSelector("system.os","linux")

# fetch all checks where the label "foo" = "bar"
client.checks.list().labelSelector("foo","bar") 
```

I haven't touched Python in a few years, so please excuse any obvious flaws in this pseudo code example. 😊

**Comment by tadeboro** [comment]
> I haven't touched Python in a few years, so please excuse any obvious flaws in this pseudo code example.

I mess around with snakes all day and still manage to butcher samples to no end, so you are safe here ;)

That being said, I would propose a few modifications to the proposed interface. I would propose that the `list()` method gains two optional parameters that will allows us to filter the responses. The code using filters would then look like this:

```
client.checks.list(
    label_selector=[
        Op.EQUAL("environment", "production"),
        Op.NOT_EQUAL("region", "us-west-2"),
        Op.MATCHES("machine", "linux-"),
    ],
    field_selector=[
        Op.IN("cpustats", "subscriptions"),
        Op.NOT_IN("slack", "handlers"),
    ],
)
```

Alternatively, we could structure this with infix operators like this:

```
client.checks.list(
    label_selector=[
        ("environment", "==", "production"),
        ("region", "!=", "us-west-2"),
        ("machine", "matches", "linux-"),
    ],
    field_selector=[
        ("cpustats", "in", "subscriptions"),
        ("slack", "noton", "handlers"),
    ],
)
```

Both would result in the following query string:

```
labelSelector=environment == "production && region != "us-west-2" && machine matches "linux-"
fieldSelector="cpustats" in check.subscriptions && "slack" not in check.handlers
```

I like the first solution a bit better because it is safer to use and can be type-checked, but apart from that, both implementations are equal.
